<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'IvyForms\\Vendor\\Psr\\Container\\' => array($vendorDir . '/psr/container/src'),
    'IvyForms\\Vendor\\PhpDocReader\\' => array($vendorDir . '/php-di/phpdoc-reader/src/PhpDocReader'),
    'IvyForms\\Vendor\\Melograno\\UsageTracker\\' => array($vendorDir . '/melograno/usage-tracker/src'),
    'IvyForms\\Vendor\\Laravel\\SerializableClosure\\' => array($vendorDir . '/laravel/serializable-closure/src'),
    'IvyForms\\Vendor\\Invoker\\' => array($vendorDir . '/php-di/invoker/src'),
    'IvyForms\\Vendor\\DI\\' => array($vendorDir . '/php-di/php-di/src'),
);
