<?php

// autoload_static.php @generated by Composer

namespace IvyForms\Vendor\Composer\Autoload;

class ComposerStaticInit767a7dee8e8836c5bc313bca945a538c
{
    public static $files = array (
        'a10106f9fc92eb44cc2a66bdeb66c2a6' => __DIR__ . '/..' . '/php-di/php-di/src/functions.php',
    );

    public static $prefixLengthsPsr4 = array (
        'I' =>
        array (
            'IvyForms\\Vendor\\Psr\\Container\\' => 30,
            'IvyForms\\Vendor\\PhpDocReader\\' => 29,
            'IvyForms\\Vendor\\Melograno\\UsageTracker\\' => 39,
            'IvyForms\\Vendor\\Laravel\\SerializableClosure\\' => 44,
            'IvyForms\\Vendor\\Invoker\\' => 24,
            'IvyForms\\Vendor\\DI\\' => 19,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'IvyForms\\Vendor\\Psr\\Container\\' =>
        array (
            0 => __DIR__ . '/..' . '/psr/container/src',
        ),
        'IvyForms\\Vendor\\PhpDocReader\\' =>
        array (
            0 => __DIR__ . '/..' . '/php-di/phpdoc-reader/src/PhpDocReader',
        ),
        'IvyForms\\Vendor\\Melograno\\UsageTracker\\' =>
        array (
            0 => __DIR__ . '/..' . '/melograno/usage-tracker/src',
        ),
        'IvyForms\\Vendor\\Laravel\\SerializableClosure\\' =>
        array (
            0 => __DIR__ . '/..' . '/laravel/serializable-closure/src',
        ),
        'IvyForms\\Vendor\\Invoker\\' =>
        array (
            0 => __DIR__ . '/..' . '/php-di/invoker/src',
        ),
        'IvyForms\\Vendor\\DI\\' =>
        array (
            0 => __DIR__ . '/..' . '/php-di/php-di/src',
        ),
    );

    public static $classMap = array (
        'IvyForms\\Vendor\\Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'IvyForms\\Vendor\\DI\\Annotation\\Inject' => __DIR__ . '/..' . '/php-di/php-di/src/Annotation/Inject.php',
        'IvyForms\\Vendor\\DI\\Annotation\\Injectable' => __DIR__ . '/..' . '/php-di/php-di/src/Annotation/Injectable.php',
        'IvyForms\\Vendor\\DI\\CompiledContainer' => __DIR__ . '/..' . '/php-di/php-di/src/CompiledContainer.php',
        'IvyForms\\Vendor\\DI\\Compiler\\Compiler' => __DIR__ . '/..' . '/php-di/php-di/src/Compiler/Compiler.php',
        'IvyForms\\Vendor\\DI\\Compiler\\ObjectCreationCompiler' => __DIR__ . '/..' . '/php-di/php-di/src/Compiler/ObjectCreationCompiler.php',
        'IvyForms\\Vendor\\DI\\Compiler\\RequestedEntryHolder' => __DIR__ . '/..' . '/php-di/php-di/src/Compiler/RequestedEntryHolder.php',
        'IvyForms\\Vendor\\DI\\Container' => __DIR__ . '/..' . '/php-di/php-di/src/Container.php',
        'IvyForms\\Vendor\\DI\\ContainerBuilder' => __DIR__ . '/..' . '/php-di/php-di/src/ContainerBuilder.php',
        'IvyForms\\Vendor\\DI\\Definition\\ArrayDefinition' => __DIR__ . '/..' . '/php-di/php-di/src/Definition/ArrayDefinition.php',
        'IvyForms\\Vendor\\DI\\Definition\\ArrayDefinitionExtension' => __DIR__ . '/..' . '/php-di/php-di/src/Definition/ArrayDefinitionExtension.php',
        'IvyForms\\Vendor\\DI\\Definition\\AutowireDefinition' => __DIR__ . '/..' . '/php-di/php-di/src/Definition/AutowireDefinition.php',
        'IvyForms\\Vendor\\DI\\Definition\\DecoratorDefinition' => __DIR__ . '/..' . '/php-di/php-di/src/Definition/DecoratorDefinition.php',
        'IvyForms\\Vendor\\DI\\Definition\\Definition' => __DIR__ . '/..' . '/php-di/php-di/src/Definition/Definition.php',
        'IvyForms\\Vendor\\DI\\Definition\\Dumper\\ObjectDefinitionDumper' => __DIR__ . '/..' . '/php-di/php-di/src/Definition/Dumper/ObjectDefinitionDumper.php',
        'IvyForms\\Vendor\\DI\\Definition\\EnvironmentVariableDefinition' => __DIR__ . '/..' . '/php-di/php-di/src/Definition/EnvironmentVariableDefinition.php',
        'IvyForms\\Vendor\\DI\\Definition\\Exception\\InvalidAnnotation' => __DIR__ . '/..' . '/php-di/php-di/src/Definition/Exception/InvalidAnnotation.php',
        'IvyForms\\Vendor\\DI\\Definition\\Exception\\InvalidDefinition' => __DIR__ . '/..' . '/php-di/php-di/src/Definition/Exception/InvalidDefinition.php',
        'IvyForms\\Vendor\\DI\\Definition\\ExtendsPreviousDefinition' => __DIR__ . '/..' . '/php-di/php-di/src/Definition/ExtendsPreviousDefinition.php',
        'IvyForms\\Vendor\\DI\\Definition\\FactoryDefinition' => __DIR__ . '/..' . '/php-di/php-di/src/Definition/FactoryDefinition.php',
        'IvyForms\\Vendor\\DI\\Definition\\Helper\\AutowireDefinitionHelper' => __DIR__ . '/..' . '/php-di/php-di/src/Definition/Helper/AutowireDefinitionHelper.php',
        'IvyForms\\Vendor\\DI\\Definition\\Helper\\CreateDefinitionHelper' => __DIR__ . '/..' . '/php-di/php-di/src/Definition/Helper/CreateDefinitionHelper.php',
        'IvyForms\\Vendor\\DI\\Definition\\Helper\\DefinitionHelper' => __DIR__ . '/..' . '/php-di/php-di/src/Definition/Helper/DefinitionHelper.php',
        'IvyForms\\Vendor\\DI\\Definition\\Helper\\FactoryDefinitionHelper' => __DIR__ . '/..' . '/php-di/php-di/src/Definition/Helper/FactoryDefinitionHelper.php',
        'IvyForms\\Vendor\\DI\\Definition\\InstanceDefinition' => __DIR__ . '/..' . '/php-di/php-di/src/Definition/InstanceDefinition.php',
        'IvyForms\\Vendor\\DI\\Definition\\ObjectDefinition' => __DIR__ . '/..' . '/php-di/php-di/src/Definition/ObjectDefinition.php',
        'IvyForms\\Vendor\\DI\\Definition\\ObjectDefinition\\MethodInjection' => __DIR__ . '/..' . '/php-di/php-di/src/Definition/ObjectDefinition/MethodInjection.php',
        'IvyForms\\Vendor\\DI\\Definition\\ObjectDefinition\\PropertyInjection' => __DIR__ . '/..' . '/php-di/php-di/src/Definition/ObjectDefinition/PropertyInjection.php',
        'IvyForms\\Vendor\\DI\\Definition\\Reference' => __DIR__ . '/..' . '/php-di/php-di/src/Definition/Reference.php',
        'IvyForms\\Vendor\\DI\\Definition\\Resolver\\ArrayResolver' => __DIR__ . '/..' . '/php-di/php-di/src/Definition/Resolver/ArrayResolver.php',
        'IvyForms\\Vendor\\DI\\Definition\\Resolver\\DecoratorResolver' => __DIR__ . '/..' . '/php-di/php-di/src/Definition/Resolver/DecoratorResolver.php',
        'IvyForms\\Vendor\\DI\\Definition\\Resolver\\DefinitionResolver' => __DIR__ . '/..' . '/php-di/php-di/src/Definition/Resolver/DefinitionResolver.php',
        'IvyForms\\Vendor\\DI\\Definition\\Resolver\\EnvironmentVariableResolver' => __DIR__ . '/..' . '/php-di/php-di/src/Definition/Resolver/EnvironmentVariableResolver.php',
        'IvyForms\\Vendor\\DI\\Definition\\Resolver\\FactoryResolver' => __DIR__ . '/..' . '/php-di/php-di/src/Definition/Resolver/FactoryResolver.php',
        'IvyForms\\Vendor\\DI\\Definition\\Resolver\\InstanceInjector' => __DIR__ . '/..' . '/php-di/php-di/src/Definition/Resolver/InstanceInjector.php',
        'IvyForms\\Vendor\\DI\\Definition\\Resolver\\ObjectCreator' => __DIR__ . '/..' . '/php-di/php-di/src/Definition/Resolver/ObjectCreator.php',
        'IvyForms\\Vendor\\DI\\Definition\\Resolver\\ParameterResolver' => __DIR__ . '/..' . '/php-di/php-di/src/Definition/Resolver/ParameterResolver.php',
        'IvyForms\\Vendor\\DI\\Definition\\Resolver\\ResolverDispatcher' => __DIR__ . '/..' . '/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php',
        'IvyForms\\Vendor\\DI\\Definition\\SelfResolvingDefinition' => __DIR__ . '/..' . '/php-di/php-di/src/Definition/SelfResolvingDefinition.php',
        'IvyForms\\Vendor\\DI\\Definition\\Source\\AnnotationBasedAutowiring' => __DIR__ . '/..' . '/php-di/php-di/src/Definition/Source/AnnotationBasedAutowiring.php',
        'IvyForms\\Vendor\\DI\\Definition\\Source\\Autowiring' => __DIR__ . '/..' . '/php-di/php-di/src/Definition/Source/Autowiring.php',
        'IvyForms\\Vendor\\DI\\Definition\\Source\\DefinitionArray' => __DIR__ . '/..' . '/php-di/php-di/src/Definition/Source/DefinitionArray.php',
        'IvyForms\\Vendor\\DI\\Definition\\Source\\DefinitionFile' => __DIR__ . '/..' . '/php-di/php-di/src/Definition/Source/DefinitionFile.php',
        'IvyForms\\Vendor\\DI\\Definition\\Source\\DefinitionNormalizer' => __DIR__ . '/..' . '/php-di/php-di/src/Definition/Source/DefinitionNormalizer.php',
        'IvyForms\\Vendor\\DI\\Definition\\Source\\DefinitionSource' => __DIR__ . '/..' . '/php-di/php-di/src/Definition/Source/DefinitionSource.php',
        'IvyForms\\Vendor\\DI\\Definition\\Source\\MutableDefinitionSource' => __DIR__ . '/..' . '/php-di/php-di/src/Definition/Source/MutableDefinitionSource.php',
        'IvyForms\\Vendor\\DI\\Definition\\Source\\NoAutowiring' => __DIR__ . '/..' . '/php-di/php-di/src/Definition/Source/NoAutowiring.php',
        'IvyForms\\Vendor\\DI\\Definition\\Source\\ReflectionBasedAutowiring' => __DIR__ . '/..' . '/php-di/php-di/src/Definition/Source/ReflectionBasedAutowiring.php',
        'IvyForms\\Vendor\\DI\\Definition\\Source\\SourceCache' => __DIR__ . '/..' . '/php-di/php-di/src/Definition/Source/SourceCache.php',
        'IvyForms\\Vendor\\DI\\Definition\\Source\\SourceChain' => __DIR__ . '/..' . '/php-di/php-di/src/Definition/Source/SourceChain.php',
        'IvyForms\\Vendor\\DI\\Definition\\StringDefinition' => __DIR__ . '/..' . '/php-di/php-di/src/Definition/StringDefinition.php',
        'IvyForms\\Vendor\\DI\\Definition\\ValueDefinition' => __DIR__ . '/..' . '/php-di/php-di/src/Definition/ValueDefinition.php',
        'IvyForms\\Vendor\\DI\\DependencyException' => __DIR__ . '/..' . '/php-di/php-di/src/DependencyException.php',
        'IvyForms\\Vendor\\DI\\FactoryInterface' => __DIR__ . '/..' . '/php-di/php-di/src/FactoryInterface.php',
        'IvyForms\\Vendor\\DI\\Factory\\RequestedEntry' => __DIR__ . '/..' . '/php-di/php-di/src/Factory/RequestedEntry.php',
        'IvyForms\\Vendor\\DI\\Invoker\\DefinitionParameterResolver' => __DIR__ . '/..' . '/php-di/php-di/src/Invoker/DefinitionParameterResolver.php',
        'IvyForms\\Vendor\\DI\\Invoker\\FactoryParameterResolver' => __DIR__ . '/..' . '/php-di/php-di/src/Invoker/FactoryParameterResolver.php',
        'IvyForms\\Vendor\\DI\\NotFoundException' => __DIR__ . '/..' . '/php-di/php-di/src/NotFoundException.php',
        'IvyForms\\Vendor\\DI\\Proxy\\ProxyFactory' => __DIR__ . '/..' . '/php-di/php-di/src/Proxy/ProxyFactory.php',
        'IvyForms\\Vendor\\Invoker\\CallableResolver' => __DIR__ . '/..' . '/php-di/invoker/src/CallableResolver.php',
        'IvyForms\\Vendor\\Invoker\\Exception\\InvocationException' => __DIR__ . '/..' . '/php-di/invoker/src/Exception/InvocationException.php',
        'IvyForms\\Vendor\\Invoker\\Exception\\NotCallableException' => __DIR__ . '/..' . '/php-di/invoker/src/Exception/NotCallableException.php',
        'IvyForms\\Vendor\\Invoker\\Exception\\NotEnoughParametersException' => __DIR__ . '/..' . '/php-di/invoker/src/Exception/NotEnoughParametersException.php',
        'IvyForms\\Vendor\\Invoker\\Invoker' => __DIR__ . '/..' . '/php-di/invoker/src/Invoker.php',
        'IvyForms\\Vendor\\Invoker\\InvokerInterface' => __DIR__ . '/..' . '/php-di/invoker/src/InvokerInterface.php',
        'IvyForms\\Vendor\\Invoker\\ParameterResolver\\AssociativeArrayResolver' => __DIR__ . '/..' . '/php-di/invoker/src/ParameterResolver/AssociativeArrayResolver.php',
        'IvyForms\\Vendor\\Invoker\\ParameterResolver\\Container\\ParameterNameContainerResolver' => __DIR__ . '/..' . '/php-di/invoker/src/ParameterResolver/Container/ParameterNameContainerResolver.php',
        'IvyForms\\Vendor\\Invoker\\ParameterResolver\\Container\\TypeHintContainerResolver' => __DIR__ . '/..' . '/php-di/invoker/src/ParameterResolver/Container/TypeHintContainerResolver.php',
        'IvyForms\\Vendor\\Invoker\\ParameterResolver\\DefaultValueResolver' => __DIR__ . '/..' . '/php-di/invoker/src/ParameterResolver/DefaultValueResolver.php',
        'IvyForms\\Vendor\\Invoker\\ParameterResolver\\NumericArrayResolver' => __DIR__ . '/..' . '/php-di/invoker/src/ParameterResolver/NumericArrayResolver.php',
        'IvyForms\\Vendor\\Invoker\\ParameterResolver\\ParameterResolver' => __DIR__ . '/..' . '/php-di/invoker/src/ParameterResolver/ParameterResolver.php',
        'IvyForms\\Vendor\\Invoker\\ParameterResolver\\ResolverChain' => __DIR__ . '/..' . '/php-di/invoker/src/ParameterResolver/ResolverChain.php',
        'IvyForms\\Vendor\\Invoker\\ParameterResolver\\TypeHintResolver' => __DIR__ . '/..' . '/php-di/invoker/src/ParameterResolver/TypeHintResolver.php',
        'IvyForms\\Vendor\\Invoker\\Reflection\\CallableReflection' => __DIR__ . '/..' . '/php-di/invoker/src/Reflection/CallableReflection.php',
        'IvyForms\\Vendor\\Laravel\\SerializableClosure\\Contracts\\Serializable' => __DIR__ . '/..' . '/laravel/serializable-closure/src/Contracts/Serializable.php',
        'IvyForms\\Vendor\\Laravel\\SerializableClosure\\Contracts\\Signer' => __DIR__ . '/..' . '/laravel/serializable-closure/src/Contracts/Signer.php',
        'IvyForms\\Vendor\\Laravel\\SerializableClosure\\Exceptions\\InvalidSignatureException' => __DIR__ . '/..' . '/laravel/serializable-closure/src/Exceptions/InvalidSignatureException.php',
        'IvyForms\\Vendor\\Laravel\\SerializableClosure\\Exceptions\\MissingSecretKeyException' => __DIR__ . '/..' . '/laravel/serializable-closure/src/Exceptions/MissingSecretKeyException.php',
        'IvyForms\\Vendor\\Laravel\\SerializableClosure\\Exceptions\\PhpVersionNotSupportedException' => __DIR__ . '/..' . '/laravel/serializable-closure/src/Exceptions/PhpVersionNotSupportedException.php',
        'IvyForms\\Vendor\\Laravel\\SerializableClosure\\SerializableClosure' => __DIR__ . '/..' . '/laravel/serializable-closure/src/SerializableClosure.php',
        'IvyForms\\Vendor\\Laravel\\SerializableClosure\\Serializers\\Native' => __DIR__ . '/..' . '/laravel/serializable-closure/src/Serializers/Native.php',
        'IvyForms\\Vendor\\Laravel\\SerializableClosure\\Serializers\\Signed' => __DIR__ . '/..' . '/laravel/serializable-closure/src/Serializers/Signed.php',
        'IvyForms\\Vendor\\Laravel\\SerializableClosure\\Signers\\Hmac' => __DIR__ . '/..' . '/laravel/serializable-closure/src/Signers/Hmac.php',
        'IvyForms\\Vendor\\Laravel\\SerializableClosure\\Support\\ClosureScope' => __DIR__ . '/..' . '/laravel/serializable-closure/src/Support/ClosureScope.php',
        'IvyForms\\Vendor\\Laravel\\SerializableClosure\\Support\\ClosureStream' => __DIR__ . '/..' . '/laravel/serializable-closure/src/Support/ClosureStream.php',
        'IvyForms\\Vendor\\Laravel\\SerializableClosure\\Support\\ReflectionClosure' => __DIR__ . '/..' . '/laravel/serializable-closure/src/Support/ReflectionClosure.php',
        'IvyForms\\Vendor\\Laravel\\SerializableClosure\\Support\\SelfReference' => __DIR__ . '/..' . '/laravel/serializable-closure/src/Support/SelfReference.php',
        'IvyForms\\Vendor\\Laravel\\SerializableClosure\\UnsignedSerializableClosure' => __DIR__ . '/..' . '/laravel/serializable-closure/src/UnsignedSerializableClosure.php',
        'IvyForms\\Vendor\\Melograno\\UsageTracker\\Collectors\\BaseCollector' => __DIR__ . '/..' . '/melograno/usage-tracker/src/Collectors/BaseCollector.php',
        'IvyForms\\Vendor\\Melograno\\UsageTracker\\Collectors\\Common\\ActivationCollector' => __DIR__ . '/..' . '/melograno/usage-tracker/src/Collectors/Common/ActivationCollector.php',
        'IvyForms\\Vendor\\Melograno\\UsageTracker\\Collectors\\Common\\WpEnvironmentCollector' => __DIR__ . '/..' . '/melograno/usage-tracker/src/Collectors/Common/WpEnvironmentCollector.php',
        'IvyForms\\Vendor\\Melograno\\UsageTracker\\Collectors\\ConsentNoticeCollectorInterface' => __DIR__ . '/..' . '/melograno/usage-tracker/src/Collectors/ConsentNoticeCollectorInterface.php',
        'IvyForms\\Vendor\\Melograno\\UsageTracker\\Collectors\\PluginCollectorInterface' => __DIR__ . '/..' . '/melograno/usage-tracker/src/Collectors/PluginCollectorInterface.php',
        'IvyForms\\Vendor\\Melograno\\UsageTracker\\Collectors\\Plugin\\AmeliaCollector' => __DIR__ . '/..' . '/melograno/usage-tracker/src/Collectors/Plugin/AmeliaCollector.php',
        'IvyForms\\Vendor\\Melograno\\UsageTracker\\Collectors\\Plugin\\AmeliaFeatureTelemetry' => __DIR__ . '/..' . '/melograno/usage-tracker/src/Collectors/Plugin/AmeliaFeatureTelemetry.php',
        'IvyForms\\Vendor\\Melograno\\UsageTracker\\Collectors\\Plugin\\IvyFormsCollector' => __DIR__ . '/..' . '/melograno/usage-tracker/src/Collectors/Plugin/IvyFormsCollector.php',
        'IvyForms\\Vendor\\Melograno\\UsageTracker\\Collectors\\Plugin\\WpDataTablesCollector' => __DIR__ . '/..' . '/melograno/usage-tracker/src/Collectors/Plugin/WpDataTablesCollector.php',
        'IvyForms\\Vendor\\Melograno\\UsageTracker\\Collectors\\Plugin\\WpDataTablesFeatureTelemetry' => __DIR__ . '/..' . '/melograno/usage-tracker/src/Collectors/Plugin/WpDataTablesFeatureTelemetry.php',
        'IvyForms\\Vendor\\Melograno\\UsageTracker\\Core\\Anonymizer' => __DIR__ . '/..' . '/melograno/usage-tracker/src/Core/Anonymizer.php',
        'IvyForms\\Vendor\\Melograno\\UsageTracker\\Core\\ConsentManager' => __DIR__ . '/..' . '/melograno/usage-tracker/src/Core/ConsentManager.php',
        'IvyForms\\Vendor\\Melograno\\UsageTracker\\Core\\ConsentNoticeService' => __DIR__ . '/..' . '/melograno/usage-tracker/src/Core/ConsentNoticeService.php',
        'IvyForms\\Vendor\\Melograno\\UsageTracker\\Core\\HttpClient' => __DIR__ . '/..' . '/melograno/usage-tracker/src/Core/HttpClient.php',
        'IvyForms\\Vendor\\Melograno\\UsageTracker\\Core\\NoticeManager' => __DIR__ . '/..' . '/melograno/usage-tracker/src/Core/NoticeManager.php',
        'IvyForms\\Vendor\\Melograno\\UsageTracker\\Core\\UsageTracker' => __DIR__ . '/..' . '/melograno/usage-tracker/src/Core/UsageTracker.php',
        'IvyForms\\Vendor\\PhpDocReader\\AnnotationException' => __DIR__ . '/..' . '/php-di/phpdoc-reader/src/PhpDocReader/AnnotationException.php',
        'IvyForms\\Vendor\\PhpDocReader\\PhpDocReader' => __DIR__ . '/..' . '/php-di/phpdoc-reader/src/PhpDocReader/PhpDocReader.php',
        'IvyForms\\Vendor\\PhpDocReader\\PhpParser\\TokenParser' => __DIR__ . '/..' . '/php-di/phpdoc-reader/src/PhpDocReader/PhpParser/TokenParser.php',
        'IvyForms\\Vendor\\PhpDocReader\\PhpParser\\UseStatementParser' => __DIR__ . '/..' . '/php-di/phpdoc-reader/src/PhpDocReader/PhpParser/UseStatementParser.php',
        'IvyForms\\Vendor\\Psr\\Container\\ContainerExceptionInterface' => __DIR__ . '/..' . '/psr/container/src/ContainerExceptionInterface.php',
        'IvyForms\\Vendor\\Psr\\Container\\ContainerInterface' => __DIR__ . '/..' . '/psr/container/src/ContainerInterface.php',
        'IvyForms\\Vendor\\Psr\\Container\\NotFoundExceptionInterface' => __DIR__ . '/..' . '/psr/container/src/NotFoundExceptionInterface.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit767a7dee8e8836c5bc313bca945a538c::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit767a7dee8e8836c5bc313bca945a538c::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit767a7dee8e8836c5bc313bca945a538c::$classMap;

        }, null, ClassLoader::class);
    }
}
