<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'a10106f9fc92eb44cc2a66bdeb66c2a6' => $vendorDir . '/php-di/php-di/src/functions.php',
);
